apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketapi
  template:
    metadata:
      labels:
        app: basketapi
    spec:
      containers:
      - name: basketapi
        image: csaymandocker/basketapi:latest
        ports:
        - containerPort: 8080
        env:
           - name: "ASPNETCORE_ENVIRONMENT"
             value: "Development"
           - name: "Urls"
             value: "http://*:8001"
           - name: "CacheSettings__ConnectionString"
             value: "basketdb-clusterip-srv:6379"
           - name: "GrpcSettings__DiscountUrl"
             value: "http://discountgrpc-clusterip-srv:8003"
           - name: "EventBusSettings__HostAddress"
             value: "amqp://guest:guest@rabbitmq-clusterip-srv:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: basketapi
spec:
  type: LoadBalancer
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: basketapi  