apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogapi
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      containers:
      - name: catalogapi
        image: csaymandocker/catalogapi:latest
        ports:
        - containerPort: 8080
        env:
           - name: "ASPNETCORE_ENVIRONMENT"
             value: "Development"
           - name: "Urls"
             value: "http://*:8000"
           - name: "ConnectionStrings__CatalogConnectionString"
             value: "Server=mssql-clusterip-srv;Database=CatalogDB;User Id=sa;Password=SwN12345678"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: catalogapi