apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountdb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountdb
  template:
    metadata:
      labels:
        app: discountdb
    spec:
      containers:
        - name: discountdb
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: "POSTGRES_USER"
              value: "admin"
            - name: "POSTGRES_PASSWORD"
              value: "admin1234"
            - name: "POSTGRES_DB"
              value: "DiscountDb"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "mendix-pgdata"
      volumes:
        - hostPath:
            path: "/home/docker/pgdata"
          name: mendix-pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: discountdb-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: discountdb
  ports:
  - name: discountdb
    protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: discountdb-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: discountdb
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432