apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountgrpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountgrpc
  template:
    metadata:
      labels:
        app: discountgrpc
    spec:
      containers:
      - name: discountgrpc
        image: csaymandocker/discountgrpc:latest
        ports:
        - containerPort: 80
        env:
           - name: "ASPNETCORE_ENVIRONMENT"
             value: "Development"
           - name: "Urls"
             value: "http://*:8003"
           - name: "ConnectionStrings__ConnectionString"
             value: "Server=discountdb-clusterip-srv;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
---
apiVersion: v1
kind: Service
metadata:
  name: discountgrpc-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: discountgrpc
  ports:
  - name: discountgrpc
    protocol: TCP
    port: 8003
    targetPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: discountgrpc
spec:
  type: LoadBalancer
  ports:
  - port: 8003
    targetPort: 8003
  selector:
    app: discountgrpc  