apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountapi
  template:
    metadata:
      labels:
        app: discountapi
    spec:
      containers:
      - name: discountapi
        image: csaymandocker/discountapi:latest
        ports:
        - containerPort: 8080
        env:
           - name: "ASPNETCORE_ENVIRONMENT"
             value: "Development"
           - name: "Urls"
             value: "http://*:8002"
           - name: "ConnectionStrings__ConnectionString"
             value: "Server=discountdb-clusterip-srv;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
---
apiVersion: v1
kind: Service
metadata:
  name: discountapi
spec:
  type: LoadBalancer
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    app: discountapi