apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotapigw
  template:
    metadata:
      labels:
        app: ocelotapigw
    spec:
      containers:
      - name: ocelotapigw
        image: csaymandocker/ocelotapigw:latest
        ports:
        - containerPort: 8080
        env:
           - name: "ASPNETCORE_ENVIRONMENT"
             value: "Development"
           - name: "Urls"
             value: "http://*:8010"
---
apiVersion: v1
kind: Service
metadata:
  name: ocelotapigw
spec:
  type: LoadBalancer
  ports:
  - port: 8010
    targetPort: 8010
  selector:
    app: ocelotapigw