apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderingapi
  template:
    metadata:
      labels:
        app: orderingapi
    spec:
      containers:
      - name: orderingapi
        image: csaymandocker/orderingapi:latest
        ports:
        - containerPort: 8080
        env:
           - name: "ASPNETCORE_ENVIRONMENT"
             value: "Development"
           - name: "Urls"
             value: "http://*:8004"
           - name: "ConnectionStrings__OrderingConnectionString"
             value: "Server=mssql-clusterip-srv;Database=OrderDB;User Id=sa;Password=SwN12345678"
           - name: "EventBusSettings__HostAddress"
             value: "amqp://guest:guest@rabbitmq-clusterip-srv:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: orderingapi
spec:
  type: LoadBalancer
  ports:
  - port: 8004
    targetPort: 8004
  selector:
    app: orderingapi