apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingaggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingaggregator
  template:
    metadata:
      labels:
        app: shoppingaggregator
    spec:
      containers:
      - name: shoppingaggregator
        image: csaymandocker/shoppingaggregator:latest
        ports:
        - containerPort: 8080
        env:
           - name: "ASPNETCORE_ENVIRONMENT"
             value: "Development"
           - name: "Urls"
             value: "http://*:8005"
           - name: "ApiSettings__CatalogUrl"
             value: "http://localhost:8000"
           - name: "ApiSettings__BasketUrl"
             value: "http://localhost:8001"
           - name: "ApiSettings__OrderingUrl"
             value: "http://localhost:8004"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingaggregator
spec:
  type: LoadBalancer
  ports:
  - port: 8005
    targetPort: 8005
  selector:
    app: shoppingaggregator