version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  sqlserverdb:
     container_name: sqlserverdb
     environment:
         SA_PASSWORD: "SwN12345678"
         ACCEPT_EULA: "Y"
     restart: always
     ports:
       - "1433:1433"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://discount.grpc"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - discountdb
    ports:
      - "8000:80"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__CatalogConnectionString=Server=sqlserverdb;Database=CatalogDB;User Id=sa;Password=SwN12345678" 
    depends_on:
      - sqlserverdb
    ports:
      - "8001:80"

  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;" 
    ports:
      - "8002:80"
    depends_on:
      - discountdb

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;" 
    ports:
      - "8003:80"
    depends_on:
      - discountdb


  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderingConnectionString=Server=sqlserverdb;Database=OrderDB;User Id=sa;Password=SwN12345678" 
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - sqlserverdb
    ports:
      - "8004:80"
